In [28]:
import pandas as pd

import re

In [29]:
df = pd.read_csv('archive/2020-05-01/ted_talks_en.csv')

In [30]:
df

,talk_id,title,speaker_1,all_speakers,occupations,about_speakers,views,recorded_date,published_date,event,native_lang,available_lang,comments,duration,topics,related_talks,url,description,transcript
0,1,Averting the climate crisis,Al Gore,{0: 'Al Gore'},{0: ['climate advocate']},{0: 'Nobel Laureate Al Gore focused the world’...,3523392,2006-02-25,2006-06-27,TED2006,en,"['ar', 'bg', 'cs', 'de', 'el', 'en', 'es', 'fa...",272.0,977,"['alternative energy', 'cars', 'climate change...","{243: 'New thinking on the climate crisis', 54...",https://www.ted.com/talks/al_gore_averting_the...,With the same humor and humanity he exuded in ...,"Thank you so much, Chris. And it's truly a gre..."
1,92,The best stats you've ever seen,Hans Rosling,{0: 'Hans Rosling'},{0: ['global health expert; data visionary']},"{0: 'In Hans Rosling’s hands, data sings. Glob...",14501685,2006-02-22,2006-06-27,TED2006,en,"['ar', 'az', 'bg', 'bn', 'bs', 'cs', 'da', 'de...",628.0,1190,"['Africa', 'Asia', 'Google', 'demo', 'economic...","{2056: ""Own your body's data"", 2296: 'A visual...",https://www.ted.com/talks/hans_rosling_the_bes...,You've never seen data presented like this. Wi...,"About 10 years ago, I took on the task to teac..."
2,7,Simplicity sells,David Pogue,{0: 'David Pogue'},{0: ['technology columnist']},{0: 'David Pogue is the personal technology co...,1920832,2006-02-24,2006-06-27,TED2006,en,"['ar', 'bg', 'de', 'el', 'en', 'es', 'fa', 'fr...",124.0,1286,"['computers', 'entertainment', 'interface desi...","{1725: '10 top time-saving tech tips', 2274: '...",https://www.ted.com/talks/david_pogue_simplici...,New York Times columnist David Pogue takes aim...,"(Music: ""The Sound of Silence,"" Simon & Garfun..."
3,53,Greening the ghetto,Majora Carter,{0: 'Majora Carter'},{0: ['activist for environmental justice']},{0: 'Majora Carter redefined the field of envi...,2664069,2006-02-26,2006-06-27,TED2006,en,"['ar', 'bg', 'bn', 'ca', 'cs', 'de', 'en', 'es...",219.0,1116,"['MacArthur grant', 'activism', 'business', 'c...",{1041: '3 stories of local eco-entrepreneurshi...,https://www.ted.com/talks/majora_carter_greeni...,"In an emotionally charged talk, MacArthur-winn...",If you're here today — and I'm very happy that...
4,66,Do schools kill creativity?,Sir Ken Robinson,{0: 'Sir Ken Robinson'},"{0: ['author', 'educator']}","{0: ""Creativity expert Sir Ken Robinson challe...",65051954,2006-02-25,2006-06-27,TED2006,en,"['af', 'ar', 'az', 'be', 'bg', 'bn', 'ca', 'cs...",4931.0,1164,"['children', 'creativity', 'culture', 'dance',...","{865: 'Bring on the learning revolution!', 173...",https://www.ted.com/talks/sir_ken_robinson_do_...,Sir Ken Robinson makes an entertaining and pro...,Good morning. How are you? (Audience) Good. It...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4000,62678,"Crisis support for the world, one text away",Nancy Lublin,{0: 'Nancy Lublin'},{0: ['health activist']},"{0: 'Nancy Lublin, cofounder and CEO of Crisis...",502934,2020-04-22,2020-04-27,TED2020: The Prequel,en,['en'],6.0,690,"['activism', 'data', 'technology', 'mental hea...",{2362: 'How data from a crisis text line is sa...,https://www.ted.com/talks/nancy_lublin_crisis_...,What if we could help people in crisis anytime...,"""I'm 14, and I want to go home."" ""My name is B..."
4001,62782,The dark history of IQ tests,Stefan C Dombrowski,{0: 'Stefan C Dombrowski'},NaN,NaN,307187,2020-04-27,2020-04-27,TED-Ed,en,"['en', 'es', 'my', 'pt-br']",NaN,346,"['TED-Ed', 'education', 'history', 'animation'...",{35386: 'How does the Rorschach inkblot test w...,https://www.ted.com/talks/stefan_c_dombrowski_...,"In 1905, psychologists Alfred Binet and Théodo...","In 1905, psychologists Alfred Binet and Théodo..."
4002,62263,"How ""policing for profit"" undermines your rights",Dick M. Carpenter II,{0: 'Dick M. Carpenter II'},{0: ['law researcher']},{0: 'Dick M. Carpenter II studies cutting edge...,464414,2019-06-22,2020-04-28,TEDxMileHigh,en,['en'],9.0,774,"['society', 'law', 'policy', 'justice system',...","{2406: 'I love being a police officer, but we ...",https://www.ted.com/talks/dick_m_carpenter_ii_...,"Many countries have an active, centuries-old l...",Picture yourself driving down the road tomorro...
4003,62784,The electrifying speeches of Sojourner Truth,Daina Ramey Berry,{0: 'Daina Ramey Berry'},NaN,NaN,56582,2020-04-28,2020-04-30,TED-Ed,en,['en'],NaN,257,"['TED-Ed', 'education', 'animation', 'United S...",{20973: 'The breathtaking courage of Harriet T...,https://www.ted.com/talks/daina_ramey_berry_th...,Isabella Baumfree was born into slavery in lat...,"In early 1828, Sojourner Truth approached the ..."
4004,62794,The most important anus in the ocean,Cella Wright,{0: 'Cella Wright'},NaN,NaN,0,2020-04-30,2020-04-30,TED-Ed,en,['en'],NaN,281,"['animals', 'TED-Ed', 'animation', 'oceans', '...","{62347: 'The bug that poops candy', 29159: 'In...",https://www.ted.com/talks/cella_wright_the_mos...,Is it a fuzzy sock? An overripe banana? A mold...,Can you guess what you’re looking at? Is it a ...

In [31]:
df.shape

(4005, 19)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4005 entries, 0 to 4004
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   talk_id         4005 non-null   int64
 1   title           4005 non-null   object
 2   speaker_1       4005 non-null   object
 3   all_speakers    4001 non-null   object
 4   occupations     3483 non-null   object
 5   about_speakers  3502 non-null   object
 6   views           4005 non-null   int64
 7   recorded_date   4004 non-null   object
 8   published_date  4005 non-null   object
 9   event           4005 non-null   object
 10  native_lang     4005 non-null   object
 11  available_lang  4005 non-null   object
 12  comments        3350 non-null   float64
 13  duration        4005 non-null   int64
 14  topics          4005 non-null   object
 15  related_talks   4005 non-null   object
 16  url             4005 non-null   object
 17  description     4005 non-null   object
 18  transcript      4005 non-null   object
dtypes: float64(1), int64(3), object(15)
memory usage: 594.6+ KB

In [33]:
df.columns

Index(['talk_id', 'title', 'speaker_1', 'all_speakers', 'occupations',
       'about_speakers', 'views', 'recorded_date', 'published_date', 'event',
       'native_lang', 'available_lang', 'comments', 'duration', 'topics',
       'related_talks', 'url', 'description', 'transcript'],
      dtype='object')

In [34]:
df[['description', 'transcript']]

,description,transcript
0,With the same humor and humanity he exuded in ...,"Thank you so much, Chris. And it's truly a gre..."
1,You've never seen data presented like this. Wi...,"About 10 years ago, I took on the task to teac..."
2,New York Times columnist David Pogue takes aim...,"(Music: ""The Sound of Silence,"" Simon & Garfun..."
3,"In an emotionally charged talk, MacArthur-winn...",If you're here today — and I'm very happy that...
4,Sir Ken Robinson makes an entertaining and pro...,Good morning. How are you? (Audience) Good. It...
...,...,...
4000,What if we could help people in crisis anytime...,"""I'm 14, and I want to go home."" ""My name is B..."
4001,"In 1905, psychologists Alfred Binet and Théodo...","In 1905, psychologists Alfred Binet and Théodo..."
4002,"Many countries have an active, centuries-old l...",Picture yourself driving down the road tomorro...
4003,Isabella Baumfree was born into slavery in lat...,"In early 1828, Sojourner Truth approached the ..."
4004,Is it a fuzzy sock? An overripe banana? A mold...,Can you guess what you’re looking at? Is it a ...

In [35]:
df['desc_word_count'] = df['description'].str.split().str.len()
df['script_word_count'] = df['transcript'].str.split().str.len()

In [36]:
df[['desc_word_count', 'script_word_count']].describe()

       desc_word_count  script_word_count
count      4005.000000        4005.000000
mean         58.195506        1796.845693
std          19.430348        1004.008431
min           9.000000           2.000000
25%          43.000000         928.000000
50%          57.000000        1753.000000
75%          72.000000        2445.000000
max         143.000000       11121.000000

In [37]:
df = df[df['desc_word_count'] > 40]

In [38]:
df

,talk_id,title,speaker_1,all_speakers,occupations,about_speakers,views,recorded_date,published_date,event,...,available_lang,comments,duration,topics,related_talks,url,description,transcript,desc_word_count,script_word_count
7,94,Let's teach religion -- all religion -- in sch...,Dan Dennett,{0: 'Dan Dennett'},"{0: ['philosopher', 'cognitive scientist']}",{0: 'Dan Dennett thinks that human consciousne...,3781244,2006-02-02,2006-07-18,TED2006,...,"['ar', 'bg', 'cs', 'de', 'el', 'en', 'es', 'fa...",919.0,1485,"['God', 'atheism', 'brain', 'cognitive science...","{71: 'A life of purpose', 2011: 'Is religion g...",https://www.ted.com/talks/dan_dennett_let_s_te...,Philosopher Dan Dennett calls for religion -- ...,It's wonderful to be back. I love this wonderf...,43,3631
8,71,A life of purpose,Rick Warren,{0: 'Rick Warren'},"{0: ['pastor', 'author']}",{0: 'Pastor Rick Warren is the author of <em>T...,3998282,2006-02-25,2006-07-18,TED2006,...,"['ar', 'bg', 'cs', 'de', 'el', 'en', 'es', 'fa...",930.0,1262,"['Christianity', 'God', 'culture', 'happiness'...","{94: ""Let's teach religion -- all religion -- ...",https://www.ted.com/talks/rick_warren_a_life_o...,"Pastor Rick Warren, author of ""The Purpose-Dri...","I'm often asked, ""What surprised you about the...",44,3468
21,21,Meet the founder of the blog revolution,Mena Trott,{0: 'Mena Trott'},"{0: ['blogger; cofounder', 'six apart']}",{0: 'Mena Trott and her husband Ben founded Si...,565712,2006-02-23,2006-08-25,TED2006,...,"['ar', 'bg', 'cs', 'de', 'el', 'en', 'es', 'fr...",52.0,1006,"['business', 'communication', 'community', 'cu...","{144: ""The Web's secret stories"", 1282: 'The t...",https://www.ted.com/talks/mena_trott_meet_the_...,"The founding mother of the blog revolution, Mo...","Over the past couple of days, as I've been pre...",42,3094
33,79,How mobile phones can fight poverty,Iqbal Quadir,{0: 'Iqbal Quadir'},"{0: ['founder', 'grameenphone']}",{0: 'Iqbal Quadir is an advocate of business a...,593410,2005-07-13,2006-10-10,TEDGlobal 2005,...,"['ar', 'bg', 'cs', 'de', 'en', 'es', 'fr', 'he...",77.0,952,"['alternative energy', 'business', 'communicat...","{270: 'The ""bottom billion""', 157: 'Patient ca...",https://www.ted.com/talks/iqbal_quadir_how_mob...,Iqbal Quadir tells how his experiences as a ki...,I'll just take you to Bangladesh for a minute....,42,2347
35,75,Why we should invest in a free press,Sasa Vucinic,{0: 'Sasa Vucinic'},{0: ['nonprofit venture capitalist']},"{0: ""Sasa Vucinic's Media Development Loan Fun...",658021,2005-07-14,2006-10-18,TEDGlobal 2005,...,"['ar', 'bg', 'de', 'en', 'es', 'fr', 'he', 'hr...",43.0,1080,"['business', 'culture', 'global issues', 'inve...","{91: ""Invest in Africa's own solutions"", 170: ...",https://www.ted.com/talks/sasa_vucinic_why_we_...,"A free press -- papers, magazines, radio, TV, ...",Video: Narrator: An event seen from one point ...,42,2721
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4000,62678,"Crisis support for the world, one text away",Nancy Lublin,{0: 'Nancy Lublin'},{0: ['health activist']},"{0: 'Nancy Lublin, cofounder and CEO of Crisis...",502934,2020-04-22,2020-04-27,TED2020: The Prequel,...,['en'],6.0,690,"['activism', 'data', 'technology', 'mental hea...",{2362: 'How data from a crisis text line is sa...,https://www.ted.com/talks/nancy_lublin_crisis_...,What if we could help people in crisis anytime...,"""I'm 14, and I want to go home."" ""My name is B...",97,1735
4001,62782,The dark history of IQ tests,Stefan C Dombrowski,{0: 'Stefan C Dombrowski'},NaN,NaN,307187,2020-04-27,2020-04-27,TED-Ed,...,"['en', 'es', 'my', 'pt-br']",NaN,346,"['TED-Ed', 'education', 'history', 'animation'...",{35386: 'How does the Rorschach inkblot test w...,https://www.ted.com/talks/stefan_c_dombrowski_...,"In 1905, psychologists Alfred Binet and Théodo...","In 1905, psychologists Alfred Binet and Théodo...",77,743
4002,62263,"How ""policing for profit"" undermines your rights",Dick M. Carpenter II,{0: 'Dick M. Carpenter II'},{0: ['law researcher']},{0: 'Dick M. Carpenter II studies cutting edge...,464414,2019-06-22,2020-04-28,TEDxMileHigh,...,['en'],9.0,774,"['society', 'law', 'policy', 'justice system',...","{2406: 'I love being a police officer, but we ...",https://www.ted.com/talks/dick_m_carpenter_ii_...,"Many countries have an active, centuries-old l...",Picture yourself driving down the road tomorro...,75,1653
4003,62784,The electrifying speeches of Sojourner Truth,Daina Ramey Berry,{0: 'Daina Ramey Berry'},NaN,NaN,56582,2020-04-28,2020-04-30,TED-Ed,...,['en'],NaN,257,"['TED-Ed', 'education', 'animation', 'United S...",{20973: 'The breathtaking courage of Harriet T...,https://www.ted.com/talks/daina_ramey_berry_th...,Isabella Baumfree was born into slavery in lat...,"In early 1828, Sojourner Truth approached the ...",72,681
4004,62794,The most important anus in the ocean,Cella Wright,{0: 'Cella Wright'},NaN,NaN,0,2020-04-30,2020-04-30,TED-Ed,...,['en'],NaN,281,"['animals', 'TED-Ed', 'animation', 'oceans', '...","{62347: 'The bug that poops candy', 29159: 'In...",https://www.ted.com/talks/cella_wright_the_mos...,Is it a fuzzy sock? An overripe banana? A mold...,Can you guess what you’re looking at? Is it a ...,88,646

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3198 entries, 7 to 4004
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   talk_id            3198 non-null   int64
 1   title              3198 non-null   object
 2   speaker_1          3198 non-null   object
 3   all_speakers       3194 non-null   object
 4   occupations        2682 non-null   object
 5   about_speakers     2698 non-null   object
 6   views              3198 non-null   int64
 7   recorded_date      3197 non-null   object
 8   published_date     3198 non-null   object
 9   event              3198 non-null   object
 10  native_lang        3198 non-null   object
 11  available_lang     3198 non-null   object
 12  comments           2561 non-null   float64
 13  duration           3198 non-null   int64
 14  topics             3198 non-null   object
 15  related_talks      3198 non-null   object
 16  url                3198 non-null   object
 17  description        3198 non-null   object
 18  transcript         3198 non-null   object
 19  desc_word_count    3198 non-null   int64
 20  script_word_count  3198 non-null   int64
dtypes: float64(1), int64(5), object(15)
memory usage: 549.7+ KB

In [40]:
df.shape

(3198, 21)

In [41]:
df[['desc_word_count', 'script_word_count']].describe()

       desc_word_count  script_word_count
count      3198.000000        3198.000000
mean         64.579737        1728.116323
std          16.173144         948.268710
min          41.000000           2.000000
25%          52.000000         908.250000
50%          63.000000        1696.500000
75%          75.000000        2315.250000
max         143.000000       11121.000000

In [42]:
df = df[df['script_word_count'] > 800]

In [43]:
df

,talk_id,title,speaker_1,all_speakers,occupations,about_speakers,views,recorded_date,published_date,event,...,available_lang,comments,duration,topics,related_talks,url,description,transcript,desc_word_count,script_word_count
7,94,Let's teach religion -- all religion -- in sch...,Dan Dennett,{0: 'Dan Dennett'},"{0: ['philosopher', 'cognitive scientist']}",{0: 'Dan Dennett thinks that human consciousne...,3781244,2006-02-02,2006-07-18,TED2006,...,"['ar', 'bg', 'cs', 'de', 'el', 'en', 'es', 'fa...",919.0,1485,"['God', 'atheism', 'brain', 'cognitive science...","{71: 'A life of purpose', 2011: 'Is religion g...",https://www.ted.com/talks/dan_dennett_let_s_te...,Philosopher Dan Dennett calls for religion -- ...,It's wonderful to be back. I love this wonderf...,43,3631
8,71,A life of purpose,Rick Warren,{0: 'Rick Warren'},"{0: ['pastor', 'author']}",{0: 'Pastor Rick Warren is the author of <em>T...,3998282,2006-02-25,2006-07-18,TED2006,...,"['ar', 'bg', 'cs', 'de', 'el', 'en', 'es', 'fa...",930.0,1262,"['Christianity', 'God', 'culture', 'happiness'...","{94: ""Let's teach religion -- all religion -- ...",https://www.ted.com/talks/rick_warren_a_life_o...,"Pastor Rick Warren, author of ""The Purpose-Dri...","I'm often asked, ""What surprised you about the...",44,3468
21,21,Meet the founder of the blog revolution,Mena Trott,{0: 'Mena Trott'},"{0: ['blogger; cofounder', 'six apart']}",{0: 'Mena Trott and her husband Ben founded Si...,565712,2006-02-23,2006-08-25,TED2006,...,"['ar', 'bg', 'cs', 'de', 'el', 'en', 'es', 'fr...",52.0,1006,"['business', 'communication', 'community', 'cu...","{144: ""The Web's secret stories"", 1282: 'The t...",https://www.ted.com/talks/mena_trott_meet_the_...,"The founding mother of the blog revolution, Mo...","Over the past couple of days, as I've been pre...",42,3094
33,79,How mobile phones can fight poverty,Iqbal Quadir,{0: 'Iqbal Quadir'},"{0: ['founder', 'grameenphone']}",{0: 'Iqbal Quadir is an advocate of business a...,593410,2005-07-13,2006-10-10,TEDGlobal 2005,...,"['ar', 'bg', 'cs', 'de', 'en', 'es', 'fr', 'he...",77.0,952,"['alternative energy', 'business', 'communicat...","{270: 'The ""bottom billion""', 157: 'Patient ca...",https://www.ted.com/talks/iqbal_quadir_how_mob...,Iqbal Quadir tells how his experiences as a ki...,I'll just take you to Bangladesh for a minute....,42,2347
35,75,Why we should invest in a free press,Sasa Vucinic,{0: 'Sasa Vucinic'},{0: ['nonprofit venture capitalist']},"{0: ""Sasa Vucinic's Media Development Loan Fun...",658021,2005-07-14,2006-10-18,TEDGlobal 2005,...,"['ar', 'bg', 'de', 'en', 'es', 'fr', 'he', 'hr...",43.0,1080,"['business', 'culture', 'global issues', 'inve...","{91: ""Invest in Africa's own solutions"", 170: ...",https://www.ted.com/talks/sasa_vucinic_why_we_...,"A free press -- papers, magazines, radio, TV, ...",Video: Narrator: An event seen from one point ...,42,2721
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,62627,An ode to living on Earth,Oliver Jeffers,{0: 'Oliver Jeffers'},"{0: ['artist', 'storyteller']}","{0: 'With a style that crackles with wry wit, ...",672908,2020-04-22,2020-04-22,TED2020: The Prequel,...,"['ar', 'en', 'fa', 'fr', 'tr']",12.0,646,"['Planets', 'art', 'poetry', 'life', 'love', '...",{44696: 'You are not alone in your loneliness'...,https://www.ted.com/talks/oliver_jeffers_an_od...,If you had to explain to a newborn what it mea...,[Oliver Jeffers] [An ode to living on Earth] H...,73,1860
3997,62341,The benefits of expressing your emotions (cons...,Artūrs Miksons,{0: 'Artūrs Miksons'},"{0: ['psychotherapist', 'psychosomatic psychia...",{0: 'Arturs is a certified doctor and works at...,112898,2018-11-02,2020-04-23,TEDxRiga,...,"['en', 'es', 'lv']",NaN,932,"['life', 'emotions', 'communication', 'stigma'...","{7592: 'The history of human emotions', 9463: ...",https://www.ted.com/talks/arturs_miksons_the_b...,Every culture assigns stigma or value to diffe...,"It's a Friday afternoon, I have finally finish...",52,2229
3999,62748,A global pandemic calls for global solutions,Larry Brilliant,"{0: 'Larry Brilliant', 1: 'Chris Anderson'}","{0: ['epidemiologist', 'philanthropist'], 1: [...","{0: ""TED Prize winner Larry Brilliant has spen...",760969,2020-04-22,2020-04-24,TED2020: The Prequel,...,"['en', 'es', 'it', 'pt-br']",37.0,941,"['coronavirus', 'pandemic', 'epidemiology', 'v...","{58: 'My wish: Help me stop pandemics', 61303:...",https://www.ted.com/talks/larry_brilliant_a_gl...,Examining the facts and figures of the coronav...,"Helen Walters: So, Chris, who's up first? Chri...",81,2415
4000,62678,"Crisis support for the world, one text away",Nancy Lublin,{0: 'Nancy Lublin'},{0: ['health activist']},"{0: 'Nancy Lublin, cofounder and CEO of Crisis...",502934,2020-04-22,2020-04-27,TED2020: The Prequel,...,['en'],6.0,690,"['activism', 'data', 'technology', 'mental hea...",{2362: 'How data from a crisis text line is sa...,https://www.ted.com/talks/nancy_lublin_crisis_...,What if we could help people in crisis anytime...,"""I'm 14, and I want to go home."" ""My name is B...",97,1735
4002,62263,"How ""policing for profit"" undermines your rights",Dick M. Carpenter II,{0: 'Dick M. Carpenter II'},{0: ['law researcher']},{0: 'Dick M. Carpenter II studies cutting edge...,464414,2019-06-22,2020-04-28,TEDxMileHigh,...,['en'],9.0,774,"['society', 'law', 'policy', 'justice system',...","{2406: 'I love being a police officer, but we ...",https://www.ted.com/talks/dick_m_carpenter_ii_...,"Many countries have an active, centuries-old l...",Picture yourself driving down the road tomorro...,75,1653

In [44]:
df.shape

(2504, 21)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2504 entries, 7 to 4002
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   talk_id            2504 non-null   int64
 1   title              2504 non-null   object
 2   speaker_1          2504 non-null   object
 3   all_speakers       2501 non-null   object
 4   occupations        2459 non-null   object
 5   about_speakers     2470 non-null   object
 6   views              2504 non-null   int64
 7   recorded_date      2503 non-null   object
 8   published_date     2504 non-null   object
 9   event              2504 non-null   object
 10  native_lang        2504 non-null   object
 11  available_lang     2504 non-null   object
 12  comments           2377 non-null   float64
 13  duration           2504 non-null   int64
 14  topics             2504 non-null   object
 15  related_talks      2504 non-null   object
 16  url                2504 non-null   object
 17  description        2504 non-null   object
 18  transcript         2504 non-null   object
 19  desc_word_count    2504 non-null   int64
 20  script_word_count  2504 non-null   int64
dtypes: float64(1), int64(5), object(15)
memory usage: 430.4+ KB

In [46]:
df[['desc_word_count', 'script_word_count']].describe()

       desc_word_count  script_word_count
count      2504.000000        2504.000000
mean         64.293131        2033.051118
std          16.934775         846.059287
min          41.000000         801.000000
25%          51.000000        1480.750000
50%          61.000000        1932.500000
75%          75.000000        2473.000000
max         143.000000       11121.000000

In [47]:
def basic_clean(text):
    text = text.lower()
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r"[^a-z0-9?!'.]", ' ', text)
    text = re.sub(r'\s+', ' ', text)
    text = text.strip()

    return text

In [48]:
df = df.copy()

In [49]:
df['clean_description'] = df['description'].apply(basic_clean)
df['clean_transcript'] = df['transcript'].apply(basic_clean)

In [50]:
df

,talk_id,title,speaker_1,all_speakers,occupations,about_speakers,views,recorded_date,published_date,event,...,duration,topics,related_talks,url,description,transcript,desc_word_count,script_word_count,clean_description,clean_transcript
7,94,Let's teach religion -- all religion -- in sch...,Dan Dennett,{0: 'Dan Dennett'},"{0: ['philosopher', 'cognitive scientist']}",{0: 'Dan Dennett thinks that human consciousne...,3781244,2006-02-02,2006-07-18,TED2006,...,1485,"['God', 'atheism', 'brain', 'cognitive science...","{71: 'A life of purpose', 2011: 'Is religion g...",https://www.ted.com/talks/dan_dennett_let_s_te...,Philosopher Dan Dennett calls for religion -- ...,It's wonderful to be back. I love this wonderf...,43,3631,philosopher dan dennett calls for religion all...,it's wonderful to be back. i love this wonderf...
8,71,A life of purpose,Rick Warren,{0: 'Rick Warren'},"{0: ['pastor', 'author']}",{0: 'Pastor Rick Warren is the author of <em>T...,3998282,2006-02-25,2006-07-18,TED2006,...,1262,"['Christianity', 'God', 'culture', 'happiness'...","{94: ""Let's teach religion -- all religion -- ...",https://www.ted.com/talks/rick_warren_a_life_o...,"Pastor Rick Warren, author of ""The Purpose-Dri...","I'm often asked, ""What surprised you about the...",44,3468,pastor rick warren author of the purpose drive...,i'm often asked what surprised you about the b...
21,21,Meet the founder of the blog revolution,Mena Trott,{0: 'Mena Trott'},"{0: ['blogger; cofounder', 'six apart']}",{0: 'Mena Trott and her husband Ben founded Si...,565712,2006-02-23,2006-08-25,TED2006,...,1006,"['business', 'communication', 'community', 'cu...","{144: ""The Web's secret stories"", 1282: 'The t...",https://www.ted.com/talks/mena_trott_meet_the_...,"The founding mother of the blog revolution, Mo...","Over the past couple of days, as I've been pre...",42,3094,the founding mother of the blog revolution mov...,over the past couple of days as i've been prep...
33,79,How mobile phones can fight poverty,Iqbal Quadir,{0: 'Iqbal Quadir'},"{0: ['founder', 'grameenphone']}",{0: 'Iqbal Quadir is an advocate of business a...,593410,2005-07-13,2006-10-10,TEDGlobal 2005,...,952,"['alternative energy', 'business', 'communicat...","{270: 'The ""bottom billion""', 157: 'Patient ca...",https://www.ted.com/talks/iqbal_quadir_how_mob...,Iqbal Quadir tells how his experiences as a ki...,I'll just take you to Bangladesh for a minute....,42,2347,iqbal quadir tells how his experiences as a ki...,i'll just take you to bangladesh for a minute....
35,75,Why we should invest in a free press,Sasa Vucinic,{0: 'Sasa Vucinic'},{0: ['nonprofit venture capitalist']},"{0: ""Sasa Vucinic's Media Development Loan Fun...",658021,2005-07-14,2006-10-18,TEDGlobal 2005,...,1080,"['business', 'culture', 'global issues', 'inve...","{91: ""Invest in Africa's own solutions"", 170: ...",https://www.ted.com/talks/sasa_vucinic_why_we_...,"A free press -- papers, magazines, radio, TV, ...",Video: Narrator: An event seen from one point ...,42,2721,a free press papers magazines radio tv blogs i...,video narrator an event seen from one point of...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,62627,An ode to living on Earth,Oliver Jeffers,{0: 'Oliver Jeffers'},"{0: ['artist', 'storyteller']}","{0: 'With a style that crackles with wry wit, ...",672908,2020-04-22,2020-04-22,TED2020: The Prequel,...,646,"['Planets', 'art', 'poetry', 'life', 'love', '...",{44696: 'You are not alone in your loneliness'...,https://www.ted.com/talks/oliver_jeffers_an_od...,If you had to explain to a newborn what it mea...,[Oliver Jeffers] [An ode to living on Earth] H...,73,1860,if you had to explain to a newborn what it mea...,oliver jeffers an ode to living on earth hello...
3997,62341,The benefits of expressing your emotions (cons...,Artūrs Miksons,{0: 'Artūrs Miksons'},"{0: ['psychotherapist', 'psychosomatic psychia...",{0: 'Arturs is a certified doctor and works at...,112898,2018-11-02,2020-04-23,TEDxRiga,...,932,"['life', 'emotions', 'communication', 'stigma'...","{7592: 'The history of human emotions', 9463: ...",https://www.ted.com/talks/arturs_miksons_the_b...,Every culture assigns stigma or value to diffe...,"It's a Friday afternoon, I have finally finish...",52,2229,every culture assigns stigma or value to diffe...,it's a friday afternoon i have finally finishe...
3999,62748,A global pandemic calls for global solutions,Larry Brilliant,"{0: 'Larry Brilliant', 1: 'Chris Anderson'}","{0: ['epidemiologist', 'philanthropist'], 1: [...","{0: ""TED Prize winner Larry Brilliant has spen...",760969,2020-04-22,2020-04-24,TED2020: The Prequel,...,941,"['coronavirus', 'pandemic', 'epidemiology', 'v...","{58: 'My wish: Help me stop pandemics', 61303:...",https://www.ted.com/talks/larry_brilliant_a_gl...,Examining the facts and figures of the coronav...,"Helen Walters: So, Chris, who's up first? Chri...",81,2415,examining the facts and figures of the coronav...,helen walters so chris who's up first? chris a...
4000,62678,"Crisis support for the world, one text away",Nancy Lublin,{0: 'Nancy Lublin'},{0: ['health activist']},"{0: 'Nancy Lublin, cofounder and CEO of Crisis...",502934,2020-04-22,2020-04-27,TED2020: The Prequel,...,690,"['activism', 'data', 'technology', 'mental hea...",{2362: 'How data from a crisis text line is sa...,https://www.ted.com/talks/nancy_lublin_crisis_...,What if we could help people in crisis anytime...,"""I'm 14, and I want to go home."" ""My name is B...",97,1735,what if we could help people in crisis anytime...,i'm 14 and i want to go home. my name is beth ...
4002,62263,"How ""policing for profit"" undermines your rights",Dick M. Carpenter II,{0: 'Dick M. Carpenter II'},{0: ['law researcher']},{0: 'Dick M. Carpenter II studies cutting edge...,464414,2019-06-22,2020-04-28,TEDxMileHigh,...,774,"['society', 'law', 'policy', 'justice system',...","{2406: 'I love being a police officer, but we ...",https://www.ted.com/talks/dick_m_carpenter_ii_...,"Many countries have an active, centuries-old l...",Picture yourself driving down the road tomorro...,75,1653,many countries have an active centuries old la...,picture yourself driving down the road tomorro...

In [51]:
df['desc_word_count'] = df['clean_description'].str.split().str.len()
df['script_word_count'] = df['clean_transcript'].str.split().str.len()

In [53]:
df[['desc_word_count', 'script_word_count']].describe()

       desc_word_count  script_word_count
count      2504.000000        2504.000000
mean         64.365016        2036.136981
std          16.936892         844.558874
min          39.000000         798.000000
25%          51.000000        1486.000000
50%          62.000000        1935.000000
75%          75.000000        2480.250000
max         142.000000       11102.000000

In [54]:
df.columns

Index(['talk_id', 'title', 'speaker_1', 'all_speakers', 'occupations',
       'about_speakers', 'views', 'recorded_date', 'published_date', 'event',
       'native_lang', 'available_lang', 'comments', 'duration', 'topics',
       'related_talks', 'url', 'description', 'transcript', 'desc_word_count',
       'script_word_count', 'clean_description', 'clean_transcript'],
      dtype='object')

In [55]:
df

,talk_id,title,speaker_1,all_speakers,occupations,about_speakers,views,recorded_date,published_date,event,...,duration,topics,related_talks,url,description,transcript,desc_word_count,script_word_count,clean_description,clean_transcript
7,94,Let's teach religion -- all religion -- in sch...,Dan Dennett,{0: 'Dan Dennett'},"{0: ['philosopher', 'cognitive scientist']}",{0: 'Dan Dennett thinks that human consciousne...,3781244,2006-02-02,2006-07-18,TED2006,...,1485,"['God', 'atheism', 'brain', 'cognitive science...","{71: 'A life of purpose', 2011: 'Is religion g...",https://www.ted.com/talks/dan_dennett_let_s_te...,Philosopher Dan Dennett calls for religion -- ...,It's wonderful to be back. I love this wonderf...,42,3593,philosopher dan dennett calls for religion all...,it's wonderful to be back. i love this wonderf...
8,71,A life of purpose,Rick Warren,{0: 'Rick Warren'},"{0: ['pastor', 'author']}",{0: 'Pastor Rick Warren is the author of <em>T...,3998282,2006-02-25,2006-07-18,TED2006,...,1262,"['Christianity', 'God', 'culture', 'happiness'...","{94: ""Let's teach religion -- all religion -- ...",https://www.ted.com/talks/rick_warren_a_life_o...,"Pastor Rick Warren, author of ""The Purpose-Dri...","I'm often asked, ""What surprised you about the...",45,3446,pastor rick warren author of the purpose drive...,i'm often asked what surprised you about the b...
21,21,Meet the founder of the blog revolution,Mena Trott,{0: 'Mena Trott'},"{0: ['blogger; cofounder', 'six apart']}",{0: 'Mena Trott and her husband Ben founded Si...,565712,2006-02-23,2006-08-25,TED2006,...,1006,"['business', 'communication', 'community', 'cu...","{144: ""The Web's secret stories"", 1282: 'The t...",https://www.ted.com/talks/mena_trott_meet_the_...,"The founding mother of the blog revolution, Mo...","Over the past couple of days, as I've been pre...",42,3051,the founding mother of the blog revolution mov...,over the past couple of days as i've been prep...
33,79,How mobile phones can fight poverty,Iqbal Quadir,{0: 'Iqbal Quadir'},"{0: ['founder', 'grameenphone']}",{0: 'Iqbal Quadir is an advocate of business a...,593410,2005-07-13,2006-10-10,TEDGlobal 2005,...,952,"['alternative energy', 'business', 'communicat...","{270: 'The ""bottom billion""', 157: 'Patient ca...",https://www.ted.com/talks/iqbal_quadir_how_mob...,Iqbal Quadir tells how his experiences as a ki...,I'll just take you to Bangladesh for a minute....,42,2333,iqbal quadir tells how his experiences as a ki...,i'll just take you to bangladesh for a minute....
35,75,Why we should invest in a free press,Sasa Vucinic,{0: 'Sasa Vucinic'},{0: ['nonprofit venture capitalist']},"{0: ""Sasa Vucinic's Media Development Loan Fun...",658021,2005-07-14,2006-10-18,TEDGlobal 2005,...,1080,"['business', 'culture', 'global issues', 'inve...","{91: ""Invest in Africa's own solutions"", 170: ...",https://www.ted.com/talks/sasa_vucinic_why_we_...,"A free press -- papers, magazines, radio, TV, ...",Video: Narrator: An event seen from one point ...,41,2711,a free press papers magazines radio tv blogs i...,video narrator an event seen from one point of...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,62627,An ode to living on Earth,Oliver Jeffers,{0: 'Oliver Jeffers'},"{0: ['artist', 'storyteller']}","{0: 'With a style that crackles with wry wit, ...",672908,2020-04-22,2020-04-22,TED2020: The Prequel,...,646,"['Planets', 'art', 'poetry', 'life', 'love', '...",{44696: 'You are not alone in your loneliness'...,https://www.ted.com/talks/oliver_jeffers_an_od...,If you had to explain to a newborn what it mea...,[Oliver Jeffers] [An ode to living on Earth] H...,73,1866,if you had to explain to a newborn what it mea...,oliver jeffers an ode to living on earth hello...
3997,62341,The benefits of expressing your emotions (cons...,Artūrs Miksons,{0: 'Artūrs Miksons'},"{0: ['psychotherapist', 'psychosomatic psychia...",{0: 'Arturs is a certified doctor and works at...,112898,2018-11-02,2020-04-23,TEDxRiga,...,932,"['life', 'emotions', 'communication', 'stigma'...","{7592: 'The history of human emotions', 9463: ...",https://www.ted.com/talks/arturs_miksons_the_b...,Every culture assigns stigma or value to diffe...,"It's a Friday afternoon, I have finally finish...",53,2222,every culture assigns stigma or value to diffe...,it's a friday afternoon i have finally finishe...
3999,62748,A global pandemic calls for global solutions,Larry Brilliant,"{0: 'Larry Brilliant', 1: 'Chris Anderson'}","{0: ['epidemiologist', 'philanthropist'], 1: [...","{0: ""TED Prize winner Larry Brilliant has spen...",760969,2020-04-22,2020-04-24,TED2020: The Prequel,...,941,"['coronavirus', 'pandemic', 'epidemiology', 'v...","{58: 'My wish: Help me stop pandemics', 61303:...",https://www.ted.com/talks/larry_brilliant_a_gl...,Examining the facts and figures of the coronav...,"Helen Walters: So, Chris, who's up first? Chri...",80,2406,examining the facts and figures of the coronav...,helen walters so chris who's up first? chris a...
4000,62678,"Crisis support for the world, one text away",Nancy Lublin,{0: 'Nancy Lublin'},{0: ['health activist']},"{0: 'Nancy Lublin, cofounder and CEO of Crisis...",502934,2020-04-22,2020-04-27,TED2020: The Prequel,...,690,"['activism', 'data', 'technology', 'mental hea...",{2362: 'How data from a crisis text line is sa...,https://www.ted.com/talks/nancy_lublin_crisis_...,What if we could help people in crisis anytime...,"""I'm 14, and I want to go home."" ""My name is B...",98,1745,what if we could help people in crisis anytime...,i'm 14 and i want to go home. my name is beth ...
4002,62263,"How ""policing for profit"" undermines your rights",Dick M. Carpenter II,{0: 'Dick M. Carpenter II'},{0: ['law researcher']},{0: 'Dick M. Carpenter II studies cutting edge...,464414,2019-06-22,2020-04-28,TEDxMileHigh,...,774,"['society', 'law', 'policy', 'justice system',...","{2406: 'I love being a police officer, but we ...",https://www.ted.com/talks/dick_m_carpenter_ii_...,"Many countries have an active, centuries-old l...",Picture yourself driving down the road tomorro...,73,1651,many countries have an active centuries old la...,picture yourself driving down the road tomorro...

In [56]:
df = df.drop(columns=['talk_id', 'native_lang', 'url', 'description', 'transcript'])

In [57]:
df

,title,speaker_1,all_speakers,occupations,about_speakers,views,recorded_date,published_date,event,available_lang,comments,duration,topics,related_talks,desc_word_count,script_word_count,clean_description,clean_transcript
7,Let's teach religion -- all religion -- in sch...,Dan Dennett,{0: 'Dan Dennett'},"{0: ['philosopher', 'cognitive scientist']}",{0: 'Dan Dennett thinks that human consciousne...,3781244,2006-02-02,2006-07-18,TED2006,"['ar', 'bg', 'cs', 'de', 'el', 'en', 'es', 'fa...",919.0,1485,"['God', 'atheism', 'brain', 'cognitive science...","{71: 'A life of purpose', 2011: 'Is religion g...",42,3593,philosopher dan dennett calls for religion all...,it's wonderful to be back. i love this wonderf...
8,A life of purpose,Rick Warren,{0: 'Rick Warren'},"{0: ['pastor', 'author']}",{0: 'Pastor Rick Warren is the author of <em>T...,3998282,2006-02-25,2006-07-18,TED2006,"['ar', 'bg', 'cs', 'de', 'el', 'en', 'es', 'fa...",930.0,1262,"['Christianity', 'God', 'culture', 'happiness'...","{94: ""Let's teach religion -- all religion -- ...",45,3446,pastor rick warren author of the purpose drive...,i'm often asked what surprised you about the b...
21,Meet the founder of the blog revolution,Mena Trott,{0: 'Mena Trott'},"{0: ['blogger; cofounder', 'six apart']}",{0: 'Mena Trott and her husband Ben founded Si...,565712,2006-02-23,2006-08-25,TED2006,"['ar', 'bg', 'cs', 'de', 'el', 'en', 'es', 'fr...",52.0,1006,"['business', 'communication', 'community', 'cu...","{144: ""The Web's secret stories"", 1282: 'The t...",42,3051,the founding mother of the blog revolution mov...,over the past couple of days as i've been prep...
33,How mobile phones can fight poverty,Iqbal Quadir,{0: 'Iqbal Quadir'},"{0: ['founder', 'grameenphone']}",{0: 'Iqbal Quadir is an advocate of business a...,593410,2005-07-13,2006-10-10,TEDGlobal 2005,"['ar', 'bg', 'cs', 'de', 'en', 'es', 'fr', 'he...",77.0,952,"['alternative energy', 'business', 'communicat...","{270: 'The ""bottom billion""', 157: 'Patient ca...",42,2333,iqbal quadir tells how his experiences as a ki...,i'll just take you to bangladesh for a minute....
35,Why we should invest in a free press,Sasa Vucinic,{0: 'Sasa Vucinic'},{0: ['nonprofit venture capitalist']},"{0: ""Sasa Vucinic's Media Development Loan Fun...",658021,2005-07-14,2006-10-18,TEDGlobal 2005,"['ar', 'bg', 'de', 'en', 'es', 'fr', 'he', 'hr...",43.0,1080,"['business', 'culture', 'global issues', 'inve...","{91: ""Invest in Africa's own solutions"", 170: ...",41,2711,a free press papers magazines radio tv blogs i...,video narrator an event seen from one point of...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,An ode to living on Earth,Oliver Jeffers,{0: 'Oliver Jeffers'},"{0: ['artist', 'storyteller']}","{0: 'With a style that crackles with wry wit, ...",672908,2020-04-22,2020-04-22,TED2020: The Prequel,"['ar', 'en', 'fa', 'fr', 'tr']",12.0,646,"['Planets', 'art', 'poetry', 'life', 'love', '...",{44696: 'You are not alone in your loneliness'...,73,1866,if you had to explain to a newborn what it mea...,oliver jeffers an ode to living on earth hello...
3997,The benefits of expressing your emotions (cons...,Artūrs Miksons,{0: 'Artūrs Miksons'},"{0: ['psychotherapist', 'psychosomatic psychia...",{0: 'Arturs is a certified doctor and works at...,112898,2018-11-02,2020-04-23,TEDxRiga,"['en', 'es', 'lv']",NaN,932,"['life', 'emotions', 'communication', 'stigma'...","{7592: 'The history of human emotions', 9463: ...",53,2222,every culture assigns stigma or value to diffe...,it's a friday afternoon i have finally finishe...
3999,A global pandemic calls for global solutions,Larry Brilliant,"{0: 'Larry Brilliant', 1: 'Chris Anderson'}","{0: ['epidemiologist', 'philanthropist'], 1: [...","{0: ""TED Prize winner Larry Brilliant has spen...",760969,2020-04-22,2020-04-24,TED2020: The Prequel,"['en', 'es', 'it', 'pt-br']",37.0,941,"['coronavirus', 'pandemic', 'epidemiology', 'v...","{58: 'My wish: Help me stop pandemics', 61303:...",80,2406,examining the facts and figures of the coronav...,helen walters so chris who's up first? chris a...
4000,"Crisis support for the world, one text away",Nancy Lublin,{0: 'Nancy Lublin'},{0: ['health activist']},"{0: 'Nancy Lublin, cofounder and CEO of Crisis...",502934,2020-04-22,2020-04-27,TED2020: The Prequel,['en'],6.0,690,"['activism', 'data', 'technology', 'mental hea...",{2362: 'How data from a crisis text line is sa...,98,1745,what if we could help people in crisis anytime...,i'm 14 and i want to go home. my name is beth ...
4002,"How ""policing for profit"" undermines your rights",Dick M. Carpenter II,{0: 'Dick M. Carpenter II'},{0: ['law researcher']},{0: 'Dick M. Carpenter II studies cutting edge...,464414,2019-06-22,2020-04-28,TEDxMileHigh,['en'],9.0,774,"['society', 'law', 'policy', 'justice system',...","{2406: 'I love being a police officer, but we ...",73,1651,many countries have an active centuries old la...,picture yourself driving down the road tomorro...

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2504 entries, 7 to 4002
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              2504 non-null   object
 1   speaker_1          2504 non-null   object
 2   all_speakers       2501 non-null   object
 3   occupations        2459 non-null   object
 4   about_speakers     2470 non-null   object
 5   views              2504 non-null   int64
 6   recorded_date      2503 non-null   object
 7   published_date     2504 non-null   object
 8   event              2504 non-null   object
 9   available_lang     2504 non-null   object
 10  comments           2377 non-null   float64
 11  duration           2504 non-null   int64
 12  topics             2504 non-null   object
 13  related_talks      2504 non-null   object
 14  desc_word_count    2504 non-null   int64
 15  script_word_count  2504 non-null   int64
 16  clean_description  2504 non-null   object
 17  clean_transcript   2504 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 371.7+ KB